### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by yonetaniryo** [upupsheep/NFWPO_Final_Code#1]
We are currently trying to extend this work and wondering if it's possible for you to add a proper license (eg MIT) to this project, so that we can fork and use it in our codebase. Thank you very much for the great work!

**Comment by redway1225** [comment]
Sorry for the late reply. We have added a MIT license to our project. Thank you for the compliment.

**Comment by yonetaniryo** [comment]
Great! Thank you very much again for your great work.
